apiVersion: apps/v1
kind: Deployment
metadata:
  name: labs-api
  labels:
    app: labs-api
spec:
  selector:
    matchLabels:
      app: labs-api
  replicas: 1
  template:
    metadata:
      labels:
        app: labs-api
    spec:
      containers:
        - name: labs-api
          image: {{ .Values.labsAPI.containers.image | quote }}
          env:
            - name: MONGO_HOST
              value: {{ .Values.labsAPI.envVars.MONGO_HOST | quote  }}
            - name: MONGO_PORT
              value: {{ .Values.labsAPI.envVars.MONGO_PORT | quote  }}
          ports:
            - name: labs-api
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: labs-api
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: labs-api
  selector:
    app: labs-api
  type: ClusterIP
